export const HIDDEN_CHAR_REACHED_BOX = 'HIDDEN_CHAR_REACHED_BOX'
export const PLAYER_CHAR_REACHED_BOX = 'PLAYER_CHAR_REACHED_BOX'
export const PLAYER_TOUCHED_BOX = 'PLAYER_TOUCHED_BOX'
export const HIDDEN_THUMB_CHAR_MOVED_TO_NEXT = 'HIDDEN_THUMB_CHAR_MOVED_TO_NEXT'
