export const HIDDEN_CHAR_REACHED_TARGET = 'HIDDEN_CHAR_REACHED_TARGET'
export const PLAYER_CHAR_REACHED_TARGET = 'PLAYER_CHAR_REACHED_TARGET'
export const PLAYER_TOUCHED_TARGET = 'PLAYER_TOUCHED_TARGET'
export const HIDDEN_THUMB_CHAR_MOVED_TO_NEXT = 'HIDDEN_THUMB_CHAR_MOVED_TO_NEXT'
